config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :planes do
    resources :bookings, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: :create
  end
  get '/bookings', to: 'bookings#index', as: :bookings
  patch 'bookings/:id/decline', to: 'bookings#decline_booking', as: :decline
  patch 'bookings/:id/confirm', to: 'bookings#confirm_booking', as: :confirm
  get 'user/:id/my_planes', to: 'users#my_planes', as: :myplanes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :plane
  validates :status, inclusion: { in: ['confirmed', 'pending', 'declined'] }
end

app/models/plane.rb
class Plane < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  geocoded_by :airfield
  after_validation :geocode, if: :will_save_change_to_airfield?
  validates :pilot, default: false
  validates :title, :description, :capacity, :autonomy, :price, :registration_number, :airfield, :model, presence: true, allow_blank: false

  mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :plane
  belongs_to :user
  validates :content, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :planes
  has_many :bookings
  has_many :reviews

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:photo, :photo_cache, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:photo, :photo_cache, :email, :password, :current_password) }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
    @bookings_for_my_planes = Booking.where(plane_id: current_user.planes.ids[0])
    @planes = policy_scope(Plane).order(created_at: :desc)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @plane = Plane.find(params[:plane_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @plane = Plane.find(params[:plane_id])
    authorize @booking
    @booking.user_id = current_user.id
    @booking.plane_id = @plane.id
    if @booking.save
      redirect_to bookings_path
    else render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @plane = Plane.find(params[:plane_id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @plane = Plane.find(params[:plane_id])
    authorize @booking
    @booking.update(booking_params)
    if @booking.save
      redirect_to bookings_path
    else render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  def confirm_booking
    skip_authorization
    @booking = Booking.find(params[:id])
    @plane = @booking.plane
    @booking.status = "confirmed"
    @booking.save
    respond_to do |format|
      format.html { redirect_to myplanes_path }
      format.js
    end
  end

  def decline_booking
    skip_authorization
    @booking = Booking.find(params[:id])
    @plane = @booking.plane
    @booking.status = "declined"
    @booking.save
    respond_to do |format|
      format.html { redirect_to myplanes_path }
      format.js
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :plane_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show
  skip_after_action :verify_policy_scoped, only: :index

  def index
    if params[:where].present? || params[:capacity].present? || params[:start].present? || params[:end].present?
      params[:capacity] = 0 if params[:capacity] == ''
      query = "planes.capacity >= :capacity"
      params[:start] = Date.today.to_s if params[:start] == ''
      params[:end] = params[:start] if params[:end] == ''
      planes = Plane.near(params[:where].to_s, 100).where(query, capacity: params[:capacity].to_s)
      @planes = []
      planes.each do |plane|
        available_arr = []
        unless plane.bookings.empty?
          plane.bookings.each do |booking|
            if (Date.parse(params[:start]) > booking.end_date) || (Date.parse(params[:end]) < booking.start_date)
              available = true
            else available = false
            end
            available_arr << available
          end
        end
        @planes << plane unless available_arr.include?(false)
      end
      @planes
    else
      @planes = policy_scope(Plane).order(created_at: :desc)
    end

    @markers = @planes.map do |plane|
      {
        lng: plane.longitude,
        lat: plane.latitude
      }
    end
  end

  def show
    @plane = Plane.find(params[:id])
    @review = Review.new # <-- This is for the review.
    @booking = Booking.new
    @marker = [{ lat: @plane.latitude, lng: @plane.longitude }]
    authorize @plane
  end

  def new
    @plane = Plane.new
    authorize @plane
  end

  def create
    @plane = Plane.new(plane_params)
    authorize @plane
    @plane.user = current_user
    if @plane.save
      redirect_to planes_path
    else
      render :new
    end
  end

  def edit
    @plane = Plane.find(params[:id])
    authorize @plane
  end

  def update
    @plane = Plane.find(params[:id])
    @plane.user_id = current_user.id
    authorize @plane
    @plane.update(plane_params)
    if @plane.save
      respond_to do |format|
      format.html { redirect_to plane_path(@plane) }
      format.js
      end
    else
      respond_to do |format|
        format.html { render 'planes/show'}
        format.js
      end
    end
  end

  def destroy
    @plane = Plane.find(params[:id])
    authorize @plane
    @plane.user = current_user
    @plane.destroy
    redirect_to planes_path
  end

  private

  def plane_params
    params.require(:plane).permit(:title, :description, :registration_number, :pilot, :autonomy, :capacity, :model, :airfield, :price, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_after_action :verify_authorized

  def create
      @plane = Plane.find(params[:plane_id])
      @review = Review.new(review_params)
      @review.plane = @plane
      @booking = Booking.new
      if @review.save
        redirect_to plane_path(@plane)
      else
        render 'planes/show'
      end
    end

    private

    def review_params
      params.require(:review).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:my_planes]

  def my_planes
    @user = current_user
    authorize @user
    @planes = current_user.planes.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_manage_booking.html.erb
<div class="modal-content" id='modal-content'>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h3 class="modal-title" id="myModalLabel">Bookings for <%= plane.model %></h3>
  </div>
  <div class="modal-body" id="modalManageBookingsBody">
    <ul class='my-plane-bookings'>
      <% plane.bookings.each do |booking| %>
      <li>
        <div class="mybookings-card">
          <div class="mybookings-info"><%= "Name: #{booking.user.name} - Date: #{booking.start_date} to #{booking.end_date} - Status:" %>
            <span class='<%= "#{booking.status}_status" %>'>
              <%= booking.status.capitalize %>
            </span>
          </div>
          <% if booking.status == 'pending' %>
            <div class="mybookings-control"><%= link_to 'Confirm', confirm_path(booking), method: :patch, remote: :true %> <%= link_to 'Decline', decline_path(booking), method: :patch, remote: :true %></div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
    <div class="modal-footer" id="modalNewBookingFooter">
    </div>
  </div>
</div>

app/views/bookings/confirm_booking.js.erb
function refreshModalConfirmed(outerHTML) {
  const newModal = document.getElementById('modal-content');
  newModal.outerHTML = outerHTML;
}

refreshModalConfirmed('<%= j render "manage_booking", plane: @plane %>');

app/views/bookings/decline_booking.js.erb
function refreshModalDeclined(outerHTML) {
  const newModal = document.getElementById('modal-content');
  newModal.outerHTML = outerHTML;
}

refreshModalDeclined('<%= j render "manage_booking", plane: @plane %>');

app/views/bookings/edit.html.erb
<h3>Edit booking</h3>

<%= simple_form_for [@plane, @booking] do |f| %>
<%= f.input :start_date %>
<%= f.input :end_date %>
<%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <h1>My bookings</h1>
    <% @bookings.each do |booking| %>
      <div class='col-xs-12 col-sm-6'>
        <%= link_to plane_booking_path(booking.plane, booking) do %>
        <% image_path = booking.plane.photo.present? ? cl_image_path(booking.plane.photo) : "" %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path %>');">
          <div class="card-description">
            <h2> <%= booking.plane.title %> </h2>
          </div>
        </div>
        <% end %>
        <div class="card-footer">
          <ul class="list-inline">
            <li><h4>Start Date: <%= booking.start_date %></h4></li>
            <li><h4>End Date: <%= booking.end_date %></h4></li>
          </ul>
          <%= link_to 'Delete Booking', plane_booking_path(booking.plane, booking), method: :delete, data: { confirm: 'Are you sure ?'} %>
          <%= link_to 'Edit Booking', edit_plane_booking_path(booking.plane, booking) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- We have this code below in case we need it on another page -->

 <!--  <div class="row">
    <h1>Future bookings for my planes</h1>
    <%# @bookings_for_my_planes.each do |booking| %>
      <div class='col-xs-12 col-sm-6'>
        <%#= link_to plane_booking_path(booking.plane, booking), class: "card-link-footer" do %>
        <%# image_path = booking.plane.photo.present? ? cl_image_path(booking.plane.photo) : "" %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%# image_path %>');">
            <div class="card-description">
              <h2> <%# booking.plane.title %> </h2>
            </div>
          </div>
        <%# end %>
        <div class="card-footer">
          <ul class="list-inline">
            <li><h4>Start Date: <%# booking.start_date %></h4></li>
            <li><h4>End Date: <%# booking.end_date %></h4></li>
          </ul>
          <h4>Status: <%# booking.status %></h4>
          <div class="btn-confirm">
            <%#= link_to 'Confirm', confirm_path(booking), class: "card-link-footer", method: :patch %>
            <%#= link_to 'Decline', decline_path(booking), class: "card-link-footer", method: :patch %>
          </div>
        </div>
        </div>
      </div>
    <%# end %>
  </div> -->

app/views/bookings/show.html.erb
<div>
  <h1> <%= "Booking for #{@booking.plane.title}" %> </h1>
</div>
<div>
  <p class="plane-image"> <%= image_tag = @booking.plane.photo.present? ? (cl_image_tag @booking.plane.photo, height: 300, width: 400, crop: :fill) : "" %> </p>
</div>
<div class="registration-model">
    Model : <%= @booking.plane.model %> - Registrations number: <%= @booking.plane.registration_number %>
</div>
<br>
<div class="booking-dates">
  <p><%= "Booking start date : #{@booking.start_date} - Booking end date : #{@booking.start_date}" %></p>
</div>
<div class="booking-other-details">
  <i class="fas fa-euro-sign"></i> <%= @booking.plane.price %> - <i class="fas fa-users"></i> <%= @booking.plane.capacity %> - <i class="fas fa-map-marked-alt"></i> <%= @booking.plane.airfield %>
</div>
<div class="booking-pilot">
  Pilot : <% if @booking.plane.pilot %>
              <i class="fas fa-check-circle"></i>
              <% else %>
              <i class="fas fa-times"></i>
            <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Click & Fly</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 50%), url('https://images.pexels.com/photos/91217/pexels-photo-91217.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');">
  <div class="banner-content">
    <div class="main-title">
      <p>
        <span id="banner-typed-text"></span>
      </p>
      <%= form_tag planes_path, method: :get, class: 'form-inline' do %>
        <div class="form-group mx-sm-3 mb-2">
        <%= text_field_tag :where,
        params[:where],
        id: "inputCity",
        class: "form-control",
        placeholder: "City"
        %>
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" name="start" class="datepicker form-control" placeholder="Start" />
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" name="end" class="datepicker form-control" placeholder="End" />
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <%= number_field_tag :capacity,
            params[:capacity],
            min: 0,
            class: "form-control",
            placeholder: "Capacity"
            %>
        </div>
        <%= submit_tag 'Go!', class: 'btn btn-primary form-control' %>
      <% end %>
      </form>
    </div>
  </div>
</div>

app/views/planes/_details.html.erb
<div id="details">
  <div class="plane-title">
    <h1> <%= plane.title %> </h1>
  </div>
  <div class="registration-model">
    Model : <%= plane.model %> - Registrations number: <%= plane.registration_number %>
  </div>
    <p class="plane-image"> <%= image_path = plane.photo.present? ? (cl_image_tag plane.photo, height: 300, width: 400, crop: :fill) : "" %> </p>
  <div class="description">
    <%= plane.description %>
  </div>
  <div class="price-capacity">
    <i class="fas fa-euro-sign"></i> <%= @plane.price %> - <i class="fas fa-users"></i> <%= plane.capacity %>
  </div>
  <div class="autonomy">
    Maximum distance : <%= plane.autonomy %> kms
  </div>
  <div class="airfield">
    <i class="fas fa-map-marked-alt"></i> <%= plane.airfield %>
  </div>
  <div class="pilot">
    Pilot : <% if plane.pilot %>
              <i class="fas fa-check-circle"></i>
              <% else %>
              <i class="fas fa-times"></i>
            <% end %>
  </div>
</div>

app/views/planes/_edit.html.erb
<div class="modal-content" id="update-modal">
  <div class="modal-header">
    <button type="button" id="close-button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h3 class="modal-title" id="myModalLabel editPlaneModal"></h3>
      <h3><%= plane.model %></h3>
    </div>
      <div class="modal-body" id="modalEditPlaneBody">
        <%= simple_form_for(plane, remote: true) do |f| %>
          <%= f.input :title %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.input :model %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :autonomy %>
          <%= f.input :capacity %>
          <%= f.input :airfield %>
          <%= f.input :registration_number %>
          <%= f.check_box :pilot %><span class="labelText">  Is There A Pilot In The Plane ?</span>
          <%= f.button :submit, "Update Plane's Info", class: 'btn btn-primary btn-lg' %>
        <% end %>
      </div>
    <div class="modal-footer" id="modalNewBookingFooter">
      <button type="button" class="btn btn-secondary btn-lg" data-dismiss="modal">Cancel</button>
    </div>
  </div>

app/views/planes/index.html.erb
<div class="container planesIndexContainer">
  <div class="row cardsResults">
    <% @planes.each do |plane| %>
      <div class="col-xs-12 col-sm-6">
        <%= link_to plane_path(plane), class: "card-link-footer" do %>
          <% image_path = plane.photo.present? ? cl_image_path(plane.photo) : "" %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path %>');">
            <div class="card-category"><%= "#{plane.autonomy} km"%></div>
            <div class="card-description">
              <h2><%= plane.title %></h2>
              <p><%= "#{plane.description.first(160)}..." %></p>
            </div>
          </div>
          <div class="card-footer">
            <ul class="list-inline">
              <li><%= plane.price %> €</li>
              <li><i class="fas fa-users"></i> <%= pluralize plane.capacity, 'passenger' %></li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <div
      id="map"
      style="width: 400px;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/planes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h3>Add a new plane</h3>

      <%= simple_form_for @plane do |f| %>
        <%= f.input :title %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :model %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :autonomy %>
        <%= f.input :capacity %>
        <%= f.input :airfield %>
        <%= f.input :registration_number %>
        <%= f.check_box :pilot %><span class="labelText">  Is There A Pilot In The Plane ?</span>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <div class="col-sm-4 col-sm-offset-4">
          <h3>Add a new plane</h3>

          <%= simple_form_for @plane do |f| %>
            <%= f.input :title %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.input :model %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.input :autonomy %>
            <%= f.input :capacity %>
            <%= f.input :airfield %>
            <%= f.input :registration_number %>
            <%= f.check_box :pilot %><span class="labelText">  Is There A Pilot In The Plane ?</span>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/planes/update.js.erb
function refreshForm(outerHTML) {
	const editForm = document.getElementById('update-modal');
	editForm.innerHTML = outerHTML;
}

function closeModal() {
	const closeButton = document.getElementById('close-button').click();
}

function refreshDetails(outerHTML) {
	const details = document.getElementById('details');
	details.outerHTML = outerHTML;
}

refreshForm('<%= j render "edit", plane: @plane %>');

<% unless @plane.errors.any? %>
	closeModal();
	refreshDetails('<%= j render "details", plane: @plane %>')	
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for([ plane, review ]) do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path do %>
    <div class="logo">
      <h3>Click&Fly</h3>
      <i class="fas fa-fighter-jet"></i>
    </div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add a Plane", new_plane_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% result_arr = [] %>
          <% if user_signed_in? %>
            <% current_user.planes.each do |plane| %>
              <% plane.bookings.each do |booking| %>
                <% if booking.status == 'pending' %>
                  <% status = true %>
                <% else %>
                  <% status = false %>
                <% end %>
                <% result_arr << status %>
              <% end %>
            <% end %>
          <% end %>
          <% if result_arr.include?(true) %>
            <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/155/large-red-circle_1f534.png", class: "status-icon avatar-icon" %>
          <% end %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to 'Booking Manager', bookings_path %>
            </li>
            <li>
              <% if result_arr.include?(true) %>
                <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/155/large-red-circle_1f534.png", class: "status-icon dropdown-icon" %>
              <% end %>
              <%= link_to 'Plane Manager', myplanes_path(current_user) %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
          <% result_arr = [] %>
          <% if user_signed_in? %>
            <% current_user.planes.each do |plane| %>
              <% plane.bookings.each do |booking| %>
                <% if booking.status == 'pending' %>
                  <% status = true %>
                <% else %>
                  <% status = false %>
                <% end %>
                <% result_arr << status %>
              <% end %>
            <% end %>
          <% end %>
          <% if result_arr.include?(true) %>
            <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/155/large-red-circle_1f534.png", class: "status-icon burger-icon" %>
          <% end %>
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'Booking Manager', bookings_path %></li>
        <li>
          <% if result_arr.include?(true) %>
            <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/155/large-red-circle_1f534.png", class: "status-icon dropdown-icon" %>
          <% end %>

          <%= link_to 'Plane Manager', bookings_path %>
          </li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>